agent_config:
    agent_version: "1.0.0"
    salt_version: "3006.19"
    url: https://api-dev.siwi.ai
    update_url: https://raw.githubusercontent.com/EdsoftIt/siwi_app/refs/heads/main/
    app_name: siwi-windows-amd64.exe
errors_hardware:
    1: 'Problema CM: Não Configurado'
    3: CM_PROB_OUT_OF_MEMORY (Memória Insuficiente)
    9: CM_PROB_INVALID_DATA (Dados Inválidos)
    10: CM_PROB_FAILED_START (Falha ao Iniciar Dispositivo)
    12: CM_PROB_NORMAL_CONFLICT (Conflito de Recursos)
    14: CM_PROB_NEED_RESTART (Reinicialização Necessária)
    16: CM_PROB_PARTIAL_LOG_CONF (Configuração Parcial)
    18: CM_PROB_REINSTALL (Reinstalação Necessária)
    19: CM_PROB_REGISTRY (Erro de Registro)
    21: CM_PROB_WILL_BE_REMOVED (Em processo de remoção)
    22: CM_PROB_DISABLED (Dispositivo Desativado)
    24: Dispositivo não está presente (Falha de detecção)
    28: CM_PROB_FAILED_INSTALL (Falha na Instalação)
    29: CM_PROB_HARDWARE_DISABLED (Desabilitado pelo Hardware/BIOS)
    31: CM_PROB_FAILED_ADD (Falha ao adicionar dispositivo)
    32: CM_PROB_DISABLED_SERVICE (Serviço Desabilitado)
    33: CM_PROB_TRADUÇÃO_FALHOU
    34: CM_PROB_NO_SOFTCONFIG (Sem configuração de software)
    35: CM_PROB_BIOS_TABLE (Erro de tabela BIOS)
    36: CM_PROB_IRQ_TRANSLATION_FAILED (Falha na tradução IRQ)
    37: CM_PROB_FAILED_DRIVER_ENTRY (Falha na entrada do driver)
    38: CM_PROB_DRIVER_FAILED_PRIOR_UNLOAD (Driver anterior falhou ao descarregar)
    39: CM_PROB_DRIVER_FAILED_LOAD (Falha ao carregar o driver)
    40: CM_PROB_DRIVER_SERVICE_KEY_INVALID (Chave de serviço inválida)
    41: CM_PROB_LEGACY_SERVICE_NO_DEVICES (Serviço herdado sem dispositivos)
    42: CM_PROB_DUPLICATE_DEVICE (Dispositivo Duplicado)
    43: CM_PROB_FAILED_POST_START (Falha física/Interrompido por erro)
    44: CM_PROB_HALTED (Interrompido)
    45: CM_PROB_PHANTOM (Dispositivo Fantasma/Desconectado)
    46: CM_PROB_SYSTEM_SHUTDOWN (Sistema em desligamento)
    47: CM_PROB_HELD_FOR_EJECT (Retido para ejeção)
    48: CM_PROB_DRIVER_BLOQUEADO (Driver impedido de carregar)
    49: CM_PROB_REGISTRY_TOO_LARGE (Registro muito grande)
    50: CM_PROB_SETPROPERTIES_FAILED (Falha ao definir propriedades)
    51: CM_PROB_ESPERANDO_UMA_DEPENDÊNCIA
    52: CM_PROB_UNSIGNED_DRIVER (Driver sem assinatura digital)
    53: CM_PROB_USED_BY_DEBUGGER (Em uso pelo depurador)
    54: CM_PROB_DEVICE_RESET (Dispositivo em reinicialização)
    55: CM_PROB_CONSOLE_LOCKED (Console Bloqueado)
    56: CM_PROB_NEED_CLASS_CONFIG (Necessita configuração de classe)
    57: CM_PROB_GUEST_ASSIGNMENT_FAILED (Falha na atribuição de convidado)
monit_config:
    cron_run_time_minutes: 1
    cron_send_time_hours: 2
    usage_cpu: 95
    usage_ram: 95
